### ISSUE TITLE
Multiple Clients on for same pin

### ISSUE THREAD

**Issue by vigneshnrfs** [disintegrator/seneca-amqp-transport#22]
This is my set up. I have three microservices. One listener and two clients. 

I am trying to create two clients to listen to the same pin 'register:*' . When one client is active, running another client throws an error.

Same as the example files:

When I run one instance of listener and one instance of client. It works fine. 
But when I try to run another instance of client, it throws an error.

**Comment by nfantone** [comment]
@vigneshnrfs What exactly are you seeing? Which error is thrown? This seems to be working fine for me:

```javascript
cd examples
AMQP_URL=amqp://<user>:<password>@<amqp_host> node listener.js

2016-04-22T14:25:54.244Z np0123ipcx0p/1461335154224/26334/- INFO	hello	Seneca/2.0.1/np0123ipcx0p/1461335154224/26334/-	
2016-04-22T14:25:54.711Z np0123ipcx0p/1461335154224/26334/- INFO	listen	{type:amqp,pin:role:create,url:amqp:/<user>:<password>@<amqp_host>,socketOptions:{foo:bar	
2016-04-22T14:25:54.895Z np0123ipcx0p/1461335154224/26334/- INFO	-	-	ACT	105u06meobi8/ko30q965g45d	name:..,plugin:define,role:seneca,seq:5,tag:undefined	plugin	amqp-transport	listen	open{type:amqp,url:amqp://<user>:<password>@<amqp_host>,exchange:{type:topic,name:seneca.topic	{did:(z95gvoq7ryg9),fixedargs:{},context:{module:{id:/home/nfantone/dev/js/seneca-amqp-transport/node_modules/s
```

And then, spawn two clients (output is the same on both):

```javascript
nfantone@thinkpad-t430 examples $ AMQP_URL=amqp://<user>:<password>@<amqp_host> node client.js
2016-04-22T14:30:41.730Z hjr8rq3ja7s2/1461335441708/26380/- INFO	hello	Seneca/2.0.1/hjr8rq3ja7s2/1461335441708/26380/-	
2016-04-22T14:30:42.166Z hjr8rq3ja7s2/1461335441708/26380/- INFO	client	{type:amqp,pin:role:create,url:amqp://amqp://<user>:<password>@<amqp_host>}	
null { pid: 26371, id: 77 } { id: 'jvks7fwz84pi/kt2zqjqwwzpq',
  accept: '0reim8mafprh/1461335439304/26371/-',
  track: [ 'hjr8rq3ja7s2/1461335441708/26380/-' ],
  time: 
   { client_sent: 1461335444187,
     listen_recv: 1461335444196,
     listen_sent: 1461335444197,
     client_recv: 1461335444202 } }

```

**Comment by vigneshnrfs** [comment]
This is my output.

Listener
```
zapstitch@vignesh-ubuntu-dell:~/Downloads/seneca-amqp-transport-develop/examples$ node listener
2016-04-22T16:07:44.661Z i1ll01479yfk/1461341264640/31243/- INFO	hello	Seneca/2.0.1/i1ll01479yfk/1461341264640/31243/-	
2016-04-22T16:07:45.044Z i1ll01479yfk/1461341264640/31243/- INFO	listen	{type:amqp,pin:role:create,url:amqp://guest:guest@localhost:5672,socketOptions:{foo:bar}}	
2016-04-22T16:07:45.212Z i1ll01479yfk/1461341264640/31243/- INFO	-	-	ACT	llomw10q1jwf/9j269q2fwwwj	name:seneca-amqp-transport,plugin:define,role:seneca,seq:5,tag:undefined	plugin	amqp-transport	listen	open	{type:amqp,url:amqp://guest:guest@localhost:5672,exchange:{type:topic,name:seneca.topic,options:{durable:true,a	{did:(dswy136fdgjq),fixedargs:{},context:{module:{id:/home/zapstitch/Downloads/seneca-amqp-transport-develop/ex



```

Running my first client
```
zapstitch@vignesh-ubuntu-dell:~/Downloads/seneca-amqp-transport-develop/examples$ node listener
2016-04-22T16:07:44.661Z i1ll01479yfk/1461341264640/31243/- INFO	hello	Seneca/2.0.1/i1ll01479yfk/1461341264640/31243/-	
2016-04-22T16:07:45.044Z i1ll01479yfk/1461341264640/31243/- INFO	listen	{type:amqp,pin:role:create,url:amqp://guest:guest@localhost:5672,socketOptions:{foo:bar}}	
2016-04-22T16:0n 7:45.212Z i1ll01479yfk/1461341264640/31243/- INFO	-	-	ACT	llomw10q1jwf/9j269q2fwwwj	name:seneca-amqp-transport,plugin:define,role:seneca,seq:5,tag:undefined	plugin	amqp-transport	listen	open	{type:amqp,url:amqp://guest:guest@localhost:5672,exchange:{type:topic,name:seneca.topic,options:{durable:true,a	{did:(dswy136fdgjq),fixedargs:{},context:{module:{id:/home/zapstitch/Downloads/seneca-amqp-transport-develop/ex

```

Running another client in another terminal:
```
zapstitch@vignesh-ubuntu-dell:~/Downloads/seneca-amqp-transport-develop/examples$ node client
2016-04-22T16:09:19.013Z 609kogdy6u6b/1461341358992/31394/- INFO	hello	Seneca/2.0.1/609kogdy6u6b/1461341358992/31394/-	
2016-04-22T16:09:19.409Z 609kogdy6u6b/1461341358992/31394/- INFO	client	{type:amqp,pin:role:create,url:amqp://guest:guest@localhost:5672}	
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'queue' of undefined
    at /home/zapstitch/Downloads/seneca-amqp-transport-develop/examples/node_modules/seneca-amqp-transport/lib/client-hook.js:52:28
    at /home/zapstitch/Downloads/seneca-amqp-transport-develop/examples/node_modules/seneca-amqp-transport/node_modules/amqplib/lib/callback_model.js:61:10
    at /home/zapstitch/Downloads/seneca-amqp-transport-develop/examples/node_modules/seneca-amqp-transport/node_modules/amqplib/lib/callback_model.js:74:5
    at reply (/home/zapstitch/Downloads/seneca-amqp-transport-develop/examples/node_modules/seneca-amqp-transport/node_modules/amqplib/lib/channel.js:127:14)
    at Channel.C.accept (/home/zapstitch/Downloads/seneca-amqp-transport-develop/examples/node_modules/seneca-amqp-transport/node_modules/amqplib/lib/channel.js:401:7)
    at Connection.mainAccept [as accept] (/home/zapstitch/Downloads/seneca-amqp-transport-develop/examples/node_modules/seneca-amqp-transport/node_modules/amqplib/lib/connection.js:63:33)
    at Socket.go (/home/zapstitch/Downloads/seneca-amqp-transport-develop/examples/node_modules/seneca-amqp-transport/node_modules/amqplib/lib/connection.js:476:48)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:419:10)

```

**Comment by nfantone** [comment]
@vigneshnrfs When "Running my first client" you seem be spawning a `listener`. Was that a copy/paste mistake?

**Comment by vigneshnrfs** [comment]
Hi... Sry. That was a copy paste mistake. 

The first client ran fine.

**Comment by nfantone** [comment]
Ok. Your error is generated from `client-hook.js:52`. I'm guessing you're facing the same bug described on #21. 

Could you please try `develop` and see if your issue goes away?

**Comment by vigneshnrfs** [comment]
@nfantone The develop branch sorts the issue out. Thanks for the fix.

**Comment by nfantone** [comment]
Fantastic. Next release should be out soon.
